config/routes.rb
Rails.application.routes.draw do

  resources :students

  root 'welcome#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
  end

  def create
    @student = Student.new(student_params)

    @student.save
    redirect_to @student
  end

  def show
    @student = Student.find(params[:id])
  end

  def index
    @students = Student.all
  end

  private
    def student_params
      params.require(:student).permit(:name, :major, :gpa)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentRecord</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Major</th>
    <th>GPA</th>
  </tr>

  <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.major %></td>
      <td><%= student.gpa %></td>
    </tr>
    <% end %>
  </table>

app/views/students/new.html.erb
<h1>New Student</h1>
<%= form_for :student, url: students_path do |f| %>
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :Major %><br>
    <%= f.text_field :major %>
  </p>

  <p>
    <%= f.label :GPA %><br>
    <%= f.text_field :gpa %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/students/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Major:</strong>
  <%= @student.major %>
</p>

<p>
  <strong>GPA:</strong>
  <%= @student.gpa %>
</p>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>